name: cvcourse
channels:
- pytorch
- menpo
- defaults
dependencies:
- jupyter
- matplotlib
- python=3.8
- scikit-learn
- scipy
- opencv3
- vlfeat
- pytorch-cpu
- torchvision-cpu
- pip
- parso
- pip:
  - visdom
